#ifndef __ROBOT_ARM_CONFIG_H__
#define __ROBOT_ARM_CONFIG_H__

#include <stdint.h>

/* HC165 采集层已经按位取反；以下逻辑电平仍需通过板端传感器测试确认。 */
#define ROBOT_ARM_S1_TRIGGERED_LEVEL 1u
#define ROBOT_ARM_S2_TRIGGERED_LEVEL 1u
#define ROBOT_ARM_S3_TRIGGERED_LEVEL 1u
#define ROBOT_ARM_S4_TRIGGERED_LEVEL 1u

/* 未取得实际最大行程前禁用软件限位；机械标定后再填写生产值。 */
#define ROBOT_ARM_X_LIMIT_ENABLED 0u
#define ROBOT_ARM_Y_LIMIT_ENABLED 0u
#define ROBOT_ARM_Z_LIMIT_ENABLED 0u
#define ROBOT_ARM_X_MIN_POSITION 0
#define ROBOT_ARM_X_MAX_POSITION INT32_MAX
#define ROBOT_ARM_Y_MIN_POSITION 0
#define ROBOT_ARM_Y_MAX_POSITION INT32_MAX
#define ROBOT_ARM_Z_MIN_POSITION 0
#define ROBOT_ARM_Z_MAX_POSITION INT32_MAX

/* 三轴 Home 均朝坐标负方向；Z- 对应向上运动。 */
#define ROBOT_ARM_X_HOME_DIRECTION (-1)
#define ROBOT_ARM_Y_HOME_DIRECTION (-1)
#define ROBOT_ARM_Z_HOME_DIRECTION (-1)

/* 逻辑测试使用短行程；固件默认仍保持禁用，防止未知距离的自动运动。 */
#ifdef ROBOT_ARM_LOGIC_TEST
#define ROBOT_ARM_X_HOME_ENABLED 1u
#define ROBOT_ARM_Y_HOME_ENABLED 1u
#define ROBOT_ARM_Z_HOME_ENABLED 1u
#define ROBOT_ARM_X_HOME_MAX_STEPS 100u
#define ROBOT_ARM_Y_HOME_MAX_STEPS 100u
#define ROBOT_ARM_Z_HOME_MAX_STEPS 100u
#define ROBOT_ARM_X_HOME_TIMEOUT_MS 1000u
#define ROBOT_ARM_Y_HOME_TIMEOUT_MS 1000u
#define ROBOT_ARM_Z_HOME_TIMEOUT_MS 1000u
#define ROBOT_ARM_HOME_FAST_SPEED 100u
#define ROBOT_ARM_HOME_SLOW_SPEED 20u
#define ROBOT_ARM_HOME_BACKOFF_STEPS 10u
#else
#define ROBOT_ARM_X_HOME_ENABLED 0u
#define ROBOT_ARM_Y_HOME_ENABLED 0u
#define ROBOT_ARM_Z_HOME_ENABLED 0u
#define ROBOT_ARM_X_HOME_MAX_STEPS 0u
#define ROBOT_ARM_Y_HOME_MAX_STEPS 0u
#define ROBOT_ARM_Z_HOME_MAX_STEPS 0u
#define ROBOT_ARM_X_HOME_TIMEOUT_MS 0u
#define ROBOT_ARM_Y_HOME_TIMEOUT_MS 0u
#define ROBOT_ARM_Z_HOME_TIMEOUT_MS 0u
#define ROBOT_ARM_HOME_FAST_SPEED 0u
#define ROBOT_ARM_HOME_SLOW_SPEED 0u
#define ROBOT_ARM_HOME_BACKOFF_STEPS 0u
#endif
#define ROBOT_ARM_X_HOME_OFFSET 0
#define ROBOT_ARM_Y_HOME_OFFSET 0
#define ROBOT_ARM_Z_HOME_OFFSET 0

/* 适配现有 DMA 驱动的默认速度，单位均为 steps/s。 */
#define ROBOT_ARM_X_DEFAULT_SPEED 1000u
#define ROBOT_ARM_Y_DEFAULT_SPEED 1000u
#define ROBOT_ARM_Z_DEFAULT_SPEED 1000u

/* 单轴超时按请求速度估算并保留四倍裕量，避免正常加减速被误判。 */
#define ROBOT_ARM_MOVE_TIMEOUT_MIN_MS 30000u
#define ROBOT_ARM_MOVE_TIMEOUT_MARGIN 4u

#endif
